### ISSUE TITLE
Develop Branch Generates Warnings when Compiling Protobuf

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-protobufs#7] opened 2021-02-10 01:51 UTC
When compiling the protobuf in the /services directory on the `develop` branch, the following warnings are generated:

```
../../reference/hedera-protobufs/services/CryptoGetAccountBalance.proto(31,1): warning : warning: Import Timestamp.proto is unused.
../../reference/hedera-protobufs/services/Freeze.proto(28,1): warning : warning: Import Duration.proto is unused. 
../../reference/hedera-protobufs/services/Freeze.proto(29,1): warning : warning: Import Timestamp.proto is unused. 
../../reference/hedera-protobufs/services/ResponseHeader.proto(28,1): warning : warning: Import TransactionResponse.proto is unused. 
../../reference/hedera-protobufs/services/ScheduleCreate.proto(29,1): warning : warning: Import Timestamp.proto is unused. 
../../reference/hedera-protobufs/services/ScheduleGetInfo.proto(32,1): warning : warning: Import ScheduleCreate.proto is unused. 
../../reference/hedera-protobufs/services/Transaction.proto(29,1): warning : warning: Import Duration.proto is unused. 
../../reference/hedera-protobufs/services/TransactionRecord.proto(31,1): warning : warning: Import CryptoTransfer.proto is unused.

```

**Comment by danielakhterov** [comment] 2021-02-17 23:31
Not that this will necessarily get merged, but this PR https://github.com/hashgraph/hedera-protobufs/pull/9 also fixes these warnings.

**Comment by steven-sheehy** [comment] 2021-09-29 04:24
Closing since it's a duplicate of https://github.com/hashgraph/hedera-protobufs/issues/82 and that one contains a more recent warning list.

**Closed by steven-sheehy** 2021-09-29 04:24 UTC
