### ISSUE TITLE
Removing unsupported proto files from the repo

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-protobufs#196] opened 2022-05-05 21:22 UTC
### Problem

A discussion on Discord brought to attention that some old proto files haven't been pulled out of the repo despite this not being supported by the network.

https://github.com/hashgraph/hedera-protobufs/blob/main/services/crypto_add_live_hash.proto

### Solution

- Remove old protos

**Comment by steven-sheehy** [comment] 2022-05-05 21:47
Duplicate of https://github.com/hashgraph/hedera-protobufs/issues/159

**Comment by jsync-swirlds** [comment] 2024-12-19 23:04
Stale.  Please reopen if still needed.

**Closed by jsync-swirlds** 2024-12-19 23:04 UTC
Labels: enhancement
